apiVersion: v1
items:
x- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: "s2i-rlgl"
    name: "s2i-rlgl"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "s2i-rlgl:latest"
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/atgreen/s2i-rlgl.git
      contextDir:
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: ImageStreamTag
          name: s2i-lisp:latest
          namespace: openshift
        forcePull: true
      type: Docker
kind: List
metadata: {}
